[icon]
prepend_dirs = [
    { name = "64Gram Desktop", text = "" },
    { name = "altair", text = "" },
    { name = "Artists", text = "" },
    { name = "Bachelor's Degree", text = "" },
    { name = "Certifications", text = "" },
    { name = "Curriculum", text = "" },
    { name = "Documentations", text = "" },
    { name = "Games", text = "" },
    { name = "home", text = "" },
    { name = "ISEE", text = "" },
    { name = "Laboratory", text = "" },
    { name = "Master's Degree", text = "" },
    { name = "mnt", text = "" },
    { name = "PDF", text = "" },
    { name = "Playlists", text = "" },
    { name = "Repository", text = "" },
    { name = "run", text = ""},
    { name = "Scholarship", text = ""},
    { name = "st", text = "" },
    { name = "Templates", text = "" },
    { name = "Tickets", text = "" },
    { name = "Theory", text = "" },
    { name = "Thesis", text = "" },
    { name = "Trash", text = "" },
    { name = "Uni's Collaborations", text = "" },
    { name = "University", text = "" },
]

